### ISSUE TITLE
Question: why not .profile?

### ISSUE THREAD

**Issue by tknerr** [guilhem-cookbooks/bash#7]
Just wondering, as I'm currently setting up an Ubuntu VM, and on Ubuntu people seem to use `.profile` rather than `.bash_profile`:
http://askubuntu.com/questions/16907/i-cant-find-bash-profile

However, when a `~/.bash_profile` exists it will be used in favor of `.profile`.

My current "workaround" is to set up a `bash_resource` like this:

``` bash
bash_profile "source-dot-profile" do
  content "source ~/.profile"
end
```

Doesn't even seem like a workaround to me because no exisiting files are mangled (even though that would be covered by the `init` profile as far as I understood).

Is this the intended way of using it? Or should there rather be an attribute for selecting which console profile to use (e.g. ".bash_profile" by default but can be set to ".profile")?

**Comment by tknerr** [comment]
Woooops. Wrong assumption here:
- `~/.bash_profile` will only be preferred over `.profile` for login shells (i.e. `ssh`, `bash -l`, etc.)
- in Ubuntu desktop the session manager will only read `.profile` but not `.bash_profile` (because GDM uses dash not bash)
- in Ubuntu opening Konsole does not run in a login shell by default

=> the net effect is that in GUI mode the `.bash_profile` is never automatically sourced on Ubuntu :-/

A possible solution would be to make [the bash profile filename here](https://github.com/optiflows-cookbooks/bash/blob/master/providers/profile.rb#L60) configurable via an attribute.

What do you think?

**Comment by guilhem** [comment]
I think the best way may be to use `.bashrc` on ubuntu

**Comment by tknerr** [comment]
FYI - just found this https://github.com/jakshi/bashd cookbook from @jakshi, which looks like it would exactly fill this gap. Will give it a try...

**Comment by tknerr** [comment]
Closing this as the question is answered and there is a viable alternative if you want to use `.bashrc` rather than `.bash_profile` (see bashd cookbook)
